Disable stack 7.8.4 builds in Travis
These are always doomed to fail, unless I backport `cosmosOf`.

Sample failures:

- https://travis-ci.org/wincent/docvim/jobs/138265665
- https://travis-ci.org/wincent/docvim/jobs/138265670

> /home/travis/build/wincent/docvim/lib/Text/Docvim/AST.hs:135:19: Not in scope:
> ‘cosmosOf’

`cosmosOf` was added in lens 4.11.1, and this version of stack has 4.7.0.1.