refactor: prefer "?" over explicit `expect()`
The error output is still readable enough; eg:

    Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
    thread 'test_lexes_corpus' panicked at 'assertion failed: `(left == right)`
      left: `1`,
     right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure